### ISSUE TITLE
Most recent update - Submission Window Issues

### ISSUE THREAD

**Issue by aearleycaw** [turnitin/moodle-mod_turnitintooltwo#22]
Hello,
I am having an issue with the sizing of the submission window within the plugin.
When clicking the submit button the window that appears is far too small to use. This has not been the same with earlier versions. (see below)

![image](https://cloud.githubusercontent.com/assets/15140497/10910781/3850c186-8239-11e5-9de0-79e91e690913.png)

Where can I find the script which affects this so I can size it appropriately?

**Comment by jmcgettrick** [comment]
This process was reworked so that the our EULA is now served to the user in the inbox rather than the submission modal. We have seen the same issue you are having and it has been because the javascript from a previous version is cached, it should be resolved by an admin purging the caches.

**Comment by aearleycaw** [comment]
All Caches have been purged, yet problem still persists.
I will now try a complete re-install and get back to you.

**Comment by aearleycaw** [comment]
Hello again, 
I am running on Win10 and have tested this on Win7 and it is no longer this size.

**Comment by jmcgettrick** [comment]
This issue has been fixed in a previous release.
