### ISSUE TITLE
Resetting Course Loads Blank Page with Turnitintooltwo

### ISSUE THREAD

**Issue by cmartintlh** [turnitin/moodle-mod_turnitintooltwo#338]
We are using Moodle 3.2.2. When resetting a course that has the turnitintooltwo mod, it loads to a blank page after the reset. We were able to get the following debugging message:

Fatal error. Using $this when not in object context in /srv/www/mod/turnitintooltwo/lib.php on line 467

Resetting a course without turnitintooltwo resets normally.

**Comment by dwinn** [comment]
Hi @cmartintlh,

Which version of the plugin are you on? We fixed this in the most recent version 2017052401 on May 24th.

**Comment by cmartintlh** [comment]
Not the latest. I was looking for any sort of open issue regarding this, and didn't see it on here, so wanted to make sure it was reported. We'll update on our side and I'll open a new ticket if it isn't resolved. Thanks for the update!
